-- Open Profile Effects library
insert into public.blur_effect_catalog (id, name, description, price, rarity, active) values
  ('decoration-a_hint_of_clove', 'A Hint Of Clove', 'Community Profile Effect', 0, 'common', true),
  ('decoration-air', 'Air', 'Community Profile Effect', 0, 'common', true),
  ('decoration-akuma', 'Akuma', 'Community Profile Effect', 0, 'common', true),
  ('decoration-arcane_sigil', 'Arcane Sigil', 'Community Profile Effect', 0, 'common', true),
  ('decoration-astronaut_helmet', 'Astronaut Helmet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-autumn_crown', 'Autumn Crown', 'Community Profile Effect', 0, 'common', true),
  ('decoration-autumns_arbor', 'Autumns Arbor', 'Community Profile Effect', 0, 'common', true),
  ('decoration-autumns_arbor_aurora', 'Autumns Arbor Aurora', 'Community Profile Effect', 0, 'common', true),
  ('decoration-baby_displacer_beast', 'Baby Displacer Beast', 'Community Profile Effect', 0, 'common', true),
  ('decoration-balance', 'Balance', 'Community Profile Effect', 0, 'common', true),
  ('decoration-batarang', 'Batarang', 'Community Profile Effect', 0, 'common', true),
  ('decoration-beamchop', 'Beamchop', 'Community Profile Effect', 0, 'common', true),
  ('decoration-black_hole', 'Black Hole', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blade_storm', 'Blade Storm', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blanket_green', 'Blanket Green', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blanket_orange', 'Blanket Orange', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blanket_pink', 'Blanket Pink', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blanket_purple', 'Blanket Purple', 'Community Profile Effect', 0, 'common', true),
  ('decoration-bloodthirsty', 'Bloodthirsty', 'Community Profile Effect', 0, 'common', true),
  ('decoration-bloodthirsty_gold', 'Bloodthirsty Gold', 'Community Profile Effect', 0, 'common', true),
  ('decoration-bloodthirsty_green', 'Bloodthirsty Green', 'Community Profile Effect', 0, 'common', true),
  ('decoration-bloomling', 'Bloomling', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blue_futuristic_ui', 'Blue Futuristic Ui', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blue_gyroscope', 'Blue Gyroscope', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blue_hyper_helmet', 'Blue Hyper Helmet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blue_shine_helmet', 'Blue Shine Helmet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blue_smoke', 'Blue Smoke', 'Community Profile Effect', 0, 'common', true),
  ('decoration-blueberry_jam', 'Blueberry Jam', 'Community Profile Effect', 0, 'common', true),
  ('decoration-bowler_hat', 'Bowler Hat', 'Community Profile Effect', 0, 'common', true),
  ('decoration-box_blue_yellow', 'Box Blue Yellow', 'Community Profile Effect', 0, 'common', true),
  ('decoration-box_green_red', 'Box Green Red', 'Community Profile Effect', 0, 'common', true),
  ('decoration-box_red_white', 'Box Red White', 'Community Profile Effect', 0, 'common', true),
  ('decoration-box_red_white_blue', 'Box Red White Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-box_white_blue', 'Box White Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-brass_beats', 'Brass Beats', 'Community Profile Effect', 0, 'common', true),
  ('decoration-bubble_tea', 'Bubble Tea', 'Community Profile Effect', 0, 'common', true),
  ('decoration-bunny', 'Bunny', 'Community Profile Effect', 0, 'common', true),
  ('decoration-bunny_zzzs', 'Bunny Zzzs', 'Community Profile Effect', 0, 'common', true),
  ('decoration-burnt_toast', 'Burnt Toast', 'Community Profile Effect', 0, 'common', true),
  ('decoration-bush_camper', 'Bush Camper', 'Community Profile Effect', 0, 'common', true),
  ('decoration-butterflies', 'Butterflies', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cammy', 'Cammy', 'Community Profile Effect', 0, 'common', true),
  ('decoration-candlelight', 'Candlelight', 'Community Profile Effect', 0, 'common', true),
  ('decoration-candlelight_crimson', 'Candlelight Crimson', 'Community Profile Effect', 0, 'common', true),
  ('decoration-candlelight_dark', 'Candlelight Dark', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cannon_fire', 'Cannon Fire', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cat_1', 'Cat 1', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cat_2', 'Cat 2', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cat_3', 'Cat 3', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cat_4', 'Cat 4', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cat_ear_headset', 'Cat Ear Headset', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cat_ears', 'Cat Ears', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cattiva', 'Cattiva', 'Community Profile Effect', 0, 'common', true),
  ('decoration-chewbert', 'Chewbert', 'Community Profile Effect', 0, 'common', true),
  ('decoration-chillet', 'Chillet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-chrysanthemums_morning', 'Chrysanthemums Morning', 'Community Profile Effect', 0, 'common', true),
  ('decoration-chrysanthemums_twilight', 'Chrysanthemums Twilight', 'Community Profile Effect', 0, 'common', true),
  ('decoration-chuck', 'Chuck', 'Community Profile Effect', 0, 'common', true),
  ('decoration-chun_li', 'Chun Li', 'Community Profile Effect', 0, 'common', true),
  ('decoration-clyde_invaders', 'Clyde Invaders', 'Community Profile Effect', 0, 'common', true),
  ('decoration-confetti_festive', 'Confetti Festive', 'Community Profile Effect', 0, 'common', true),
  ('decoration-confetti_fire', 'Confetti Fire', 'Community Profile Effect', 0, 'common', true),
  ('decoration-confetti_ice', 'Confetti Ice', 'Community Profile Effect', 0, 'common', true),
  ('decoration-confetti_mint', 'Confetti Mint', 'Community Profile Effect', 0, 'common', true),
  ('decoration-confetti_star', 'Confetti Star', 'Community Profile Effect', 0, 'common', true),
  ('decoration-confetti_vaporwave', 'Confetti Vaporwave', 'Community Profile Effect', 0, 'common', true),
  ('decoration-constellations', 'Constellations', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cottage_home', 'Cottage Home', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cozy_cat', 'Cozy Cat', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cozy_headphones', 'Cozy Headphones', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cozy_post_it', 'Cozy Post It', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cozy_post_it_festive', 'Cozy Post It Festive', 'Community Profile Effect', 0, 'common', true),
  ('decoration-crystal_ball_blue', 'Crystal Ball Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-crystal_ball_purple', 'Crystal Ball Purple', 'Community Profile Effect', 0, 'common', true),
  ('decoration-crystal_elk', 'Crystal Elk', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cybernetic', 'Cybernetic', 'Community Profile Effect', 0, 'common', true),
  ('decoration-cypher_neural_theft', 'Cypher Neural Theft', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dancing_fairies', 'Dancing Fairies', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dandelion_duo', 'Dandelion Duo', 'Community Profile Effect', 0, 'common', true),
  ('decoration-deaths_edge', 'Deaths Edge', 'Community Profile Effect', 0, 'common', true),
  ('decoration-defensive_shield', 'Defensive Shield', 'Community Profile Effect', 0, 'common', true),
  ('decoration-depresso', 'Depresso', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dice_azure', 'Dice Azure', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dice_violet', 'Dice Violet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-digital_sunrise', 'Digital Sunrise', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dismay', 'Dismay', 'Community Profile Effect', 0, 'common', true),
  ('decoration-disxcore_headset', 'Disxcore Headset', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dog_1', 'Dog 1', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dog_2', 'Dog 2', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dog_3', 'Dog 3', 'Community Profile Effect', 0, 'common', true),
  ('decoration-donut', 'Donut', 'Community Profile Effect', 0, 'common', true),
  ('decoration-doodlezard', 'Doodlezard', 'Community Profile Effect', 0, 'common', true),
  ('decoration-doodling', 'Doodling', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dragons_smile', 'Dragons Smile', 'Community Profile Effect', 0, 'common', true),
  ('decoration-dusk_and_dawn', 'Dusk And Dawn', 'Community Profile Effect', 0, 'common', true),
  ('decoration-earth', 'Earth', 'Community Profile Effect', 0, 'common', true),
  ('decoration-eldritch_ring', 'Eldritch Ring', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fairy_sprites_blue', 'Fairy Sprites Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fairy_sprites_pink', 'Fairy Sprites Pink', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fall_leaves', 'Fall Leaves', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fall_leaves_scarlet', 'Fall Leaves Scarlet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fall_leaves_woodland', 'Fall Leaves Woodland', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fan_flourish', 'Fan Flourish', 'Community Profile Effect', 0, 'common', true),
  ('decoration-feelin_awe', 'Feelin Awe', 'Community Profile Effect', 0, 'common', true),
  ('decoration-feelin_nervous', 'Feelin Nervous', 'Community Profile Effect', 0, 'common', true),
  ('decoration-feelin_panic', 'Feelin Panic', 'Community Profile Effect', 0, 'common', true),
  ('decoration-feelin_scrumptious', 'Feelin Scrumptious', 'Community Profile Effect', 0, 'common', true),
  ('decoration-firecrackers', 'Firecrackers', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fishbones', 'Fishbones', 'Community Profile Effect', 0, 'common', true),
  ('decoration-flame_chompers', 'Flame Chompers', 'Community Profile Effect', 0, 'common', true),
  ('decoration-flaming_sword', 'Flaming Sword', 'Community Profile Effect', 0, 'common', true),
  ('decoration-floral_harmony', 'Floral Harmony', 'Community Profile Effect', 0, 'common', true),
  ('decoration-floral_harmony_sunburst', 'Floral Harmony Sunburst', 'Community Profile Effect', 0, 'common', true),
  ('decoration-flower_clouds', 'Flower Clouds', 'Community Profile Effect', 0, 'common', true),
  ('decoration-flux_alchemy', 'Flux Alchemy', 'Community Profile Effect', 0, 'common', true),
  ('decoration-forest', 'Forest', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fox_hat_chestnut', 'Fox Hat Chestnut', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fox_hat_snow', 'Fox Hat Snow', 'Community Profile Effect', 0, 'common', true),
  ('decoration-frag_out', 'Frag Out', 'Community Profile Effect', 0, 'common', true),
  ('decoration-freezer_bunny_lovebug', 'Freezer Bunny Lovebug', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fresh_pine', 'Fresh Pine', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fresh_pine_cinnamon', 'Fresh Pine Cinnamon', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fresh_pine_ribbon', 'Fresh Pine Ribbon', 'Community Profile Effect', 0, 'common', true),
  ('decoration-frog_1', 'Frog 1', 'Community Profile Effect', 0, 'common', true),
  ('decoration-frog_3', 'Frog 3', 'Community Profile Effect', 0, 'common', true),
  ('decoration-frog_angry', 'Frog Angry', 'Community Profile Effect', 0, 'common', true),
  ('decoration-frog_derpy', 'Frog Derpy', 'Community Profile Effect', 0, 'common', true),
  ('decoration-frog_hat', 'Frog Hat', 'Community Profile Effect', 0, 'common', true),
  ('decoration-fuchsia_agent', 'Fuchsia Agent', 'Community Profile Effect', 0, 'common', true),
  ('decoration-gary_the_snail', 'Gary The Snail', 'Community Profile Effect', 0, 'common', true),
  ('decoration-gawblehop', 'Gawblehop', 'Community Profile Effect', 0, 'common', true),
  ('decoration-gelatinous_cube_blue', 'Gelatinous Cube Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-gelatinous_cube_green', 'Gelatinous Cube Green', 'Community Profile Effect', 0, 'common', true),
  ('decoration-ghosts', 'Ghosts', 'Community Profile Effect', 0, 'common', true),
  ('decoration-glop', 'Glop', 'Community Profile Effect', 0, 'common', true),
  ('decoration-glowing_runes', 'Glowing Runes', 'Community Profile Effect', 0, 'common', true),
  ('decoration-goblin_stinkums', 'Goblin Stinkums', 'Community Profile Effect', 0, 'common', true),
  ('decoration-good_ol_pepper', 'Good Ol Pepper', 'Community Profile Effect', 0, 'common', true),
  ('decoration-graveyard_cat', 'Graveyard Cat', 'Community Profile Effect', 0, 'common', true),
  ('decoration-green_fried_egg', 'Green Fried Egg', 'Community Profile Effect', 0, 'common', true),
  ('decoration-green_futuristic_ui', 'Green Futuristic Ui', 'Community Profile Effect', 0, 'common', true),
  ('decoration-green_gyroscope', 'Green Gyroscope', 'Community Profile Effect', 0, 'common', true),
  ('decoration-green_headset', 'Green Headset', 'Community Profile Effect', 0, 'common', true),
  ('decoration-green_hyper_helmet', 'Green Hyper Helmet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-green_shine_helmet', 'Green Shine Helmet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-green_smoke', 'Green Smoke', 'Community Profile Effect', 0, 'common', true),
  ('decoration-group_hug', 'Group Hug', 'Community Profile Effect', 0, 'common', true),
  ('decoration-guile', 'Guile', 'Community Profile Effect', 0, 'common', true),
  ('decoration-hailey', 'Hailey', 'Community Profile Effect', 0, 'common', true),
  ('decoration-heartbloom', 'Heartbloom', 'Community Profile Effect', 0, 'common', true),
  ('decoration-helmsman', 'Helmsman', 'Community Profile Effect', 0, 'common', true),
  ('decoration-hex_lights', 'Hex Lights', 'Community Profile Effect', 0, 'common', true),
  ('decoration-honeyblossom', 'Honeyblossom', 'Community Profile Effect', 0, 'common', true),
  ('decoration-hood_crimson', 'Hood Crimson', 'Community Profile Effect', 0, 'common', true),
  ('decoration-hood_dark', 'Hood Dark', 'Community Profile Effect', 0, 'common', true),
  ('decoration-hot_shot', 'Hot Shot', 'Community Profile Effect', 0, 'common', true),
  ('decoration-hugh_the_rainbow', 'Hugh The Rainbow', 'Community Profile Effect', 0, 'common', true),
  ('decoration-ice_cube', 'Ice Cube', 'Community Profile Effect', 0, 'common', true),
  ('decoration-icicle_gleaming', 'Icicle Gleaming', 'Community Profile Effect', 0, 'common', true),
  ('decoration-icicle_snowing', 'Icicle Snowing', 'Community Profile Effect', 0, 'common', true),
  ('decoration-im_a_clown', 'Im A Clown', 'Community Profile Effect', 0, 'common', true),
  ('decoration-imagination', 'Imagination', 'Community Profile Effect', 0, 'common', true),
  ('decoration-implant', 'Implant', 'Community Profile Effect', 0, 'common', true),
  ('decoration-in_love', 'In Love', 'Community Profile Effect', 0, 'common', true),
  ('decoration-in_tears', 'In Tears', 'Community Profile Effect', 0, 'common', true),
  ('decoration-jack_o_lantern', 'Jack O Lantern', 'Community Profile Effect', 0, 'common', true),
  ('decoration-jeff_the_land_shark', 'Jeff The Land Shark', 'Community Profile Effect', 0, 'common', true),
  ('decoration-juri', 'Juri', 'Community Profile Effect', 0, 'common', true),
  ('decoration-kabuto', 'Kabuto', 'Community Profile Effect', 0, 'common', true),
  ('decoration-ken', 'Ken', 'Community Profile Effect', 0, 'common', true),
  ('decoration-ki_energy', 'Ki Energy', 'Community Profile Effect', 0, 'common', true),
  ('decoration-kitsune', 'Kitsune', 'Community Profile Effect', 0, 'common', true),
  ('decoration-lamball', 'Lamball', 'Community Profile Effect', 0, 'common', true),
  ('decoration-lightning', 'Lightning', 'Community Profile Effect', 0, 'common', true),
  ('decoration-lofi_girl_outfit', 'Lofi Girl Outfit', 'Community Profile Effect', 0, 'common', true),
  ('decoration-los_santos', 'Los Santos', 'Community Profile Effect', 0, 'common', true),
  ('decoration-lotus_flower', 'Lotus Flower', 'Community Profile Effect', 0, 'common', true),
  ('decoration-lucky_envelopes', 'Lucky Envelopes', 'Community Profile Effect', 0, 'common', true),
  ('decoration-lunar_lanterns', 'Lunar Lanterns', 'Community Profile Effect', 0, 'common', true),
  ('decoration-m_bison', 'M Bison', 'Community Profile Effect', 0, 'common', true),
  ('decoration-magic_portal_blue', 'Magic Portal Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-magic_portal_purple', 'Magic Portal Purple', 'Community Profile Effect', 0, 'common', true),
  ('decoration-magical_potion', 'Magical Potion', 'Community Profile Effect', 0, 'common', true),
  ('decoration-magical_wand_green', 'Magical Wand Green', 'Community Profile Effect', 0, 'common', true),
  ('decoration-magical_wand_purple', 'Magical Wand Purple', 'Community Profile Effect', 0, 'common', true),
  ('decoration-malefic_crown', 'Malefic Crown', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mallow_jump', 'Mallow Jump', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mech_flora', 'Mech Flora', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mermaid_serenade', 'Mermaid Serenade', 'Community Profile Effect', 0, 'common', true),
  ('decoration-midnight_sorceress', 'Midnight Sorceress', 'Community Profile Effect', 0, 'common', true),
  ('decoration-minions', 'Minions', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mokoko', 'Mokoko', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mooncaps_blue', 'Mooncaps Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mooncaps_pink', 'Mooncaps Pink', 'Community Profile Effect', 0, 'common', true),
  ('decoration-musclebob', 'Musclebob', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mushroom_1', 'Mushroom 1', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mushroom_2', 'Mushroom 2', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mushroom_3', 'Mushroom 3', 'Community Profile Effect', 0, 'common', true),
  ('decoration-mushroom_4', 'Mushroom 4', 'Community Profile Effect', 0, 'common', true),
  ('decoration-neon_nibbles', 'Neon Nibbles', 'Community Profile Effect', 0, 'common', true),
  ('decoration-new_year_2024', 'New Year 2024', 'Community Profile Effect', 0, 'common', true),
  ('decoration-new_year_2025', 'New Year 2025', 'Community Profile Effect', 0, 'common', true),
  ('decoration-oasis', 'Oasis', 'Community Profile Effect', 0, 'common', true),
  ('decoration-omens_cowl', 'Omens Cowl', 'Community Profile Effect', 0, 'common', true),
  ('decoration-oni_mask', 'Oni Mask', 'Community Profile Effect', 0, 'common', true),
  ('decoration-owlbear_cub', 'Owlbear Cub', 'Community Profile Effect', 0, 'common', true),
  ('decoration-owlbear_cub_snowy', 'Owlbear Cub Snowy', 'Community Profile Effect', 0, 'common', true),
  ('decoration-pal_sphere', 'Pal Sphere', 'Community Profile Effect', 0, 'common', true),
  ('decoration-patrick_star', 'Patrick Star', 'Community Profile Effect', 0, 'common', true),
  ('decoration-phoenix', 'Phoenix', 'Community Profile Effect', 0, 'common', true),
  ('decoration-pink_futuristic_ui', 'Pink Futuristic Ui', 'Community Profile Effect', 0, 'common', true),
  ('decoration-pink_gyroscope', 'Pink Gyroscope', 'Community Profile Effect', 0, 'common', true),
  ('decoration-pink_headset', 'Pink Headset', 'Community Profile Effect', 0, 'common', true),
  ('decoration-pink_hyper_helmet', 'Pink Hyper Helmet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-pink_shine_helmet', 'Pink Shine Helmet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-pink_smoke', 'Pink Smoke', 'Community Profile Effect', 0, 'common', true),
  ('decoration-pipedream', 'Pipedream', 'Community Profile Effect', 0, 'common', true),
  ('decoration-pirate_captain', 'Pirate Captain', 'Community Profile Effect', 0, 'common', true),
  ('decoration-playful_lofi_cat', 'Playful Lofi Cat', 'Community Profile Effect', 0, 'common', true),
  ('decoration-polar_bear_hat', 'Polar Bear Hat', 'Community Profile Effect', 0, 'common', true),
  ('decoration-powered_by_shimmer', 'Powered By Shimmer', 'Community Profile Effect', 0, 'common', true),
  ('decoration-rage', 'Rage', 'Community Profile Effect', 0, 'common', true),
  ('decoration-rec_room_lightning', 'Rec Room Lightning', 'Community Profile Effect', 0, 'common', true),
  ('decoration-red_lantern', 'Red Lantern', 'Community Profile Effect', 0, 'common', true),
  ('decoration-reynas_leer', 'Reynas Leer', 'Community Profile Effect', 0, 'common', true),
  ('decoration-rift_butterfly', 'Rift Butterfly', 'Community Profile Effect', 0, 'common', true),
  ('decoration-ryu', 'Ryu', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sakura', 'Sakura', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sakura_gyoiko', 'Sakura Gyoiko', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sakura_ink', 'Sakura Ink', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sakura_pink', 'Sakura Pink', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sakura_ukon', 'Sakura Ukon', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sakura_warrior', 'Sakura Warrior', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sandy_cheeks', 'Sandy Cheeks', 'Community Profile Effect', 0, 'common', true),
  ('decoration-santa_cat_ears', 'Santa Cat Ears', 'Community Profile Effect', 0, 'common', true),
  ('decoration-saw', 'Saw', 'Community Profile Effect', 0, 'common', true),
  ('decoration-scallywag', 'Scallywag', 'Community Profile Effect', 0, 'common', true),
  ('decoration-selyne', 'Selyne', 'Community Profile Effect', 0, 'common', true),
  ('decoration-shadow', 'Shadow', 'Community Profile Effect', 0, 'common', true),
  ('decoration-shield_potion', 'Shield Potion', 'Community Profile Effect', 0, 'common', true),
  ('decoration-shocked', 'Shocked', 'Community Profile Effect', 0, 'common', true),
  ('decoration-shurikens_mask', 'Shurikens Mask', 'Community Profile Effect', 0, 'common', true),
  ('decoration-skull_medallion', 'Skull Medallion', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sleepy_chilledcow', 'Sleepy Chilledcow', 'Community Profile Effect', 0, 'common', true),
  ('decoration-slither_n_snack', 'Slither N Snack', 'Community Profile Effect', 0, 'common', true),
  ('decoration-snakes_hug', 'Snakes Hug', 'Community Profile Effect', 0, 'common', true),
  ('decoration-snowglobe', 'Snowglobe', 'Community Profile Effect', 0, 'common', true),
  ('decoration-snowglobe_blue', 'Snowglobe Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-snowglobe_green', 'Snowglobe Green', 'Community Profile Effect', 0, 'common', true),
  ('decoration-snowglobe_pink', 'Snowglobe Pink', 'Community Profile Effect', 0, 'common', true),
  ('decoration-snowglobe_wood', 'Snowglobe Wood', 'Community Profile Effect', 0, 'common', true),
  ('decoration-soul_leaving_body', 'Soul Leaving Body', 'Community Profile Effect', 0, 'common', true),
  ('decoration-spirit_embers', 'Spirit Embers', 'Community Profile Effect', 0, 'common', true),
  ('decoration-spongebob', 'Spongebob', 'Community Profile Effect', 0, 'common', true),
  ('decoration-spooky_cat_ears', 'Spooky Cat Ears', 'Community Profile Effect', 0, 'common', true),
  ('decoration-spooky_cat_ears_midnight', 'Spooky Cat Ears Midnight', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sproutling', 'Sproutling', 'Community Profile Effect', 0, 'common', true),
  ('decoration-starry_eyed', 'Starry Eyed', 'Community Profile Effect', 0, 'common', true),
  ('decoration-steampunk_cat_ears', 'Steampunk Cat Ears', 'Community Profile Effect', 0, 'common', true),
  ('decoration-stinkums', 'Stinkums', 'Community Profile Effect', 0, 'common', true),
  ('decoration-straw_hat', 'Straw Hat', 'Community Profile Effect', 0, 'common', true),
  ('decoration-street_fighter_6_battle_field', 'Street Fighter 6 Battle Field', 'Community Profile Effect', 0, 'common', true),
  ('decoration-string_lights', 'String Lights', 'Community Profile Effect', 0, 'common', true),
  ('decoration-string_lights_aurora', 'String Lights Aurora', 'Community Profile Effect', 0, 'common', true),
  ('decoration-string_lights_dusk', 'String Lights Dusk', 'Community Profile Effect', 0, 'common', true),
  ('decoration-string_lights_ember', 'String Lights Ember', 'Community Profile Effect', 0, 'common', true),
  ('decoration-string_lights_mix', 'String Lights Mix', 'Community Profile Effect', 0, 'common', true),
  ('decoration-study_session', 'Study Session', 'Community Profile Effect', 0, 'common', true),
  ('decoration-sweat_drops', 'Sweat Drops', 'Community Profile Effect', 0, 'common', true),
  ('decoration-teacup_blue', 'Teacup Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-teacup_orange', 'Teacup Orange', 'Community Profile Effect', 0, 'common', true),
  ('decoration-teacup_pink', 'Teacup Pink', 'Community Profile Effect', 0, 'common', true),
  ('decoration-teacup_red', 'Teacup Red', 'Community Profile Effect', 0, 'common', true),
  ('decoration-tga_controller', 'Tga Controller', 'Community Profile Effect', 0, 'common', true),
  ('decoration-the_anomaly', 'The Anomaly', 'Community Profile Effect', 0, 'common', true),
  ('decoration-the_atlas_gauntlets', 'The Atlas Gauntlets', 'Community Profile Effect', 0, 'common', true),
  ('decoration-the_hexcore', 'The Hexcore', 'Community Profile Effect', 0, 'common', true),
  ('decoration-the_mark', 'The Mark', 'Community Profile Effect', 0, 'common', true),
  ('decoration-the_monster_you_created', 'The Monster You Created', 'Community Profile Effect', 0, 'common', true),
  ('decoration-the_petal_pack', 'The Petal Pack', 'Community Profile Effect', 0, 'common', true),
  ('decoration-timekeepers_clock', 'Timekeepers Clock', 'Community Profile Effect', 0, 'common', true),
  ('decoration-torgal_puppy', 'Torgal Puppy', 'Community Profile Effect', 0, 'common', true),
  ('decoration-treasure_and_key', 'Treasure And Key', 'Community Profile Effect', 0, 'common', true),
  ('decoration-ufo', 'Ufo', 'Community Profile Effect', 0, 'common', true),
  ('decoration-unicorn', 'Unicorn', 'Community Profile Effect', 0, 'common', true),
  ('decoration-uwu_xp', 'Uwu Xp', 'Community Profile Effect', 0, 'common', true),
  ('decoration-valorant_champions_2024', 'Valorant Champions 2024', 'Community Profile Effect', 0, 'common', true),
  ('decoration-victory_crown', 'Victory Crown', 'Community Profile Effect', 0, 'common', true),
  ('decoration-viper_poison_cloud', 'Viper Poison Cloud', 'Community Profile Effect', 0, 'common', true),
  ('decoration-wallach_spaceport', 'Wallach Spaceport', 'Community Profile Effect', 0, 'common', true),
  ('decoration-warp_helmet', 'Warp Helmet', 'Community Profile Effect', 0, 'common', true),
  ('decoration-water', 'Water', 'Community Profile Effect', 0, 'common', true),
  ('decoration-wingman_boba', 'Wingman Boba', 'Community Profile Effect', 0, 'common', true),
  ('decoration-wingmans_got_it', 'Wingmans Got It', 'Community Profile Effect', 0, 'common', true),
  ('decoration-winkle', 'Winkle', 'Community Profile Effect', 0, 'common', true),
  ('decoration-witch_hat_midnight', 'Witch Hat Midnight', 'Community Profile Effect', 0, 'common', true),
  ('decoration-witch_hat_plum', 'Witch Hat Plum', 'Community Profile Effect', 0, 'common', true),
  ('decoration-wizard_hat_blue', 'Wizard Hat Blue', 'Community Profile Effect', 0, 'common', true),
  ('decoration-wizard_hat_purple', 'Wizard Hat Purple', 'Community Profile Effect', 0, 'common', true),
  ('decoration-wizards_staff', 'Wizards Staff', 'Community Profile Effect', 0, 'common', true),
  ('decoration-wolf_morph', 'Wolf Morph', 'Community Profile Effect', 0, 'common', true),
  ('decoration-yoru_dimensional_drift', 'Yoru Dimensional Drift', 'Community Profile Effect', 0, 'common', true),
  ('decoration-zombie_food', 'Zombie Food', 'Community Profile Effect', 0, 'common', true),
  ('decoration-zombie_food_purple', 'Zombie Food Purple', 'Community Profile Effect', 0, 'common', true);
create or replace function public.blur_equip_effect(p_effect_id text default null)
returns text
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_effect_id is null then
    delete from public.blur_effect_equipped where user_id = auth.uid();
    return null;
  end if;
  if not exists (
    select 1 from public.blur_effect_catalog
    where id = p_effect_id and active = true
  ) then
    raise exception 'Profile Effect not found';
  end if;
  insert into public.blur_effect_equipped(user_id, effect_id, updated_at)
    values (auth.uid(), p_effect_id, now())
    on conflict (user_id) do update
      set effect_id = excluded.effect_id, updated_at = now();
  return p_effect_id;
end;
$$;
grant execute on function public.blur_equip_effect(text) to authenticated;
notify pgrst, 'reload schema';
